config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :price_per_night, presence: true
  validates :number_of_guests, numericality: {only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flats, only: %i[show update destroy edit]
  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def edit; end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  def update
    if @flat.update(params_flat)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @flat = Flat.new(params_flat)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_flats
    @flat = Flat.find(params[:id])
  end

  def params_flat
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>
<%= render "form", flats: @flats %>

app/views/flats/index.html.erb
<div class="container mt-3">

  <div class="row">
    <div class="col-12">
      <h1 class="justify-content-center">All our flats (4)</h1>
    </div>
  </div>

  <div class="row">
  <% @flats.each do |flat| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="width: auto;">
          <img src='https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200' class="card-img-top" alt="...">
          <div class="card-body" style="background-color: #FAFAFA">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <i class="fa-solid fa-euro-sign"><%= flat.price_per_night %></i>
            <i class="fa-solid fa-people-roof"><%= flat.number_of_guests %></i>
          </div>
          <ul class="nav m-2 justify-content-around">
            <li class="nav-item">
              <%= link_to "More info", flat_path(flat), class:"link-primary" %>
            </li>
            <li class="nav-item">
              <%= link_to "Edit", edit_flat_path(flat), class: "link-info" %>
            </li>
            <li class="nav-item">
              <%= link_to "Remove", flats_path, data: {turbo_method: :delete, turbo_confirm: "Really sure ?"}, class:"link-danger" %>
            </li>
          </ul>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flats: @flats %>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')" >
</div>
<div class="container margin-top-negative">
  <div class="row">
    <div class= "col-8">
      <div class= "flat-show-card">
        <h1><%= @flat.name %></h1><br>
        <p><%= @flat.address %></p>
      </div>
      <div class= "flat-show-card">
      <h2>A bit more about this flat...</h2>
        <%= @flat.description %><br>
        <div class="map" style='background-image: url("https://trailheadtechnology.com/wp-content/uploads/2022/12/map-default-1536x761.png.webp")'></div>
      </div>
    </div>
    <div class= "col-4">
      <div class="flat-show-card">
        <h5>Book this place:</h5>
        <div class="input-group">
          <span class="input-group-text" id="start-date-label">From:</span>
          <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
        </div>
        <div class="input-group mt-2">
          <span class="input-group-text" id="end-date-label">To:</span>
          <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
        </div>
        <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <p><%= @flat.price_per_night %> € per night</p>
        <p><%= @flat.number_of_guests %> persons</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "Simple Airbnb", flats_path, class:"lead", style: "color: grey"%>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
          <button class="btn btn-outline-secondary" type="submit"><a href="/flats/new">Add Flat</a></button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>